language: julia
notifications:
  email: false
julia:
  - 1.4
  - nightly
after_success:
  - julia -e 'cd(Pkg.dir("FiniteStateMachine")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
