name = "FiniteStateMachine"
uuid = "96d663bc-7ccb-4a8f-a6f5-76bc8e71f284"
authors = ["Martin Kosch"]
version = "0.1.0"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
